port: 9595
ip: 0.0.0.0
sources:
  - name: gizi-sample
    gitUrl: https://gitlab.com/zkochan/gizi-sample.git
buckets:
  - name: sample
    source: gizi-sample
    branch: master
  - name: sample-2
    source: gizi-sample
    branch: foo
